### ISSUE TITLE
A comment or some type of a discussion plugin would be helpful

### ISSUE THREAD

**Issue by zspine** [gabriel-detassigny/simple-blog#1]
Hi @gabriel-detassigny ,
I really liked your post https://www.detassigny.net/posts/1/design-pattern-1-value-object. It's really useful. But it make sense to put some type of a comment section to discuss the topic with other developers.

Cheers

**Comment by gabriel-detassigny** [comment]
Hi @zspine , thanks for your feedback! I'm glad you liked the article 🙂  
Comments are definitely something I'm going to look at in the near future.
I just need to determine the best way to implement them!

**Comment by gabriel-detassigny** [comment]
I've just finished adding my own comment section. It's a very basic one as I didn't want to depend on a third party solution for it. Hopefully that should do the job, but I might improve it in the future if necessary
